name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: zmkfirmware/zmk-dev-arm:stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize west
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build Left (central)
        run: |
          west build -s zmk/app -d build/left -b seeeduino_xiao -- -DSHIELD=corne_xiao_left

      - name: Build Right
        run: |
          west build -s zmk/app -d build/right -b seeeduino_xiao -- -DSHIELD=corne_xiao_right

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2
